# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
    name: git-gateway
    branch: master
    site_domain: https://tiago-sciencia.netlify.com/
    repo: tisciencia/tiago-sciencia-blog

publish_mode: editorial_workflow
media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
  
collections: # A list of collections the CMS should be able to edit
    - name: posts
      label: Post
      editor:
        preview: true
      folder: content/posts
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      create: true # Allow users to create new documents in this collection
      fields: # The fields each document in this collection have
        - {label: Template, name: template, widget: hidden, default: SinglePost}
        - {label: Title, name: title, widget: string}
        - label: 'Status'
          name: 'status'
          widget: 'select'
          options: ["Published", "Featured", "Draft"]
          default: 'Published'
        - {label: Date / Order, name: date, widget: date}
        - {label: Featured Image, name: featuredImage, widget: image, required: false}
        - {label: Excerpt, name: excerpt, widget: text}
        - {label: Content, name: body, widget: markdown}
        - label: "Categories"
          name: "categories"
          widget: "list"
          required: false
          fields:
            - label: "Category"
              name: "category"
              widget: "relation"
              collection: "postCategories"
              searchFields: ["title"]
              valueField: "title"
        - label: "Meta"
          required: false
          name: "meta"
          widget: "object"
          fields:
            - {label: Title, name: title, widget: string, required: false}
            - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
            - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
            - {label: Noindex, name: noindex, widget: boolean, required: false}
  